### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by iD4rksid3** [lockedbyte/cryptovenom#1]
With a freshly installed Kali I had to install two packages, or otherwise install requirements (pip install -r ) would fail.
the packages are: 
libmpc-dev
libssl-dev

**Comment by lockedbyte** [comment]
I think I patched it a few hours ago... if you look now at the setup.py file those dependencies are now installed via apt-get...


Thank you anyways!


If you still have problems with deps in setup.py reply this comment!
