### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by truesamurai** [lockedbyte/cryptovenom#3]
I get this error when i do setup.py:

Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    import commands,sys,os
ModuleNotFoundError: No module named 'commands'

I am on latest version of Kali.

**Comment by lockedbyte** [comment]
Hi, thanks for your report. Actually CryptoVenom does not support Python3. Use Python2 instead. I'll update CryptoVenom as soon as possible to run also over Python3 too.

**Comment by truesamurai** [comment]
Thanks for your feedback. I did not think of that. 
I tried again with python2 and now its working fine.
Thanks for the great tool.

**Comment by lockedbyte** [comment]
In case of finding more issues report them, I'll awnser as soon as I can.

Thank you!
