### ISSUE TITLE
keep program running

### ISSUE THREAD

**Issue by truesamurai** [lockedbyte/cryptovenom#4]
I really like this tool it works great. Was looking for something like this a long time.
Not a bug but more a feature request:
when i am doing encoding/decoding , then the program closes and I need to start again with every string.
Can you keep the program running so I dont have to do ./cryptovenom.py everytime.
Sometimes I have multiple strings I want to encode /decode and then I have to start the programm every time.

**Comment by lockedbyte** [comment]
Yes, you mean a while loop keeping always main menu opened unless "exit" string is entered right?

I'll leave this issue opened until I add it.

**Comment by truesamurai** [comment]
Yes that would be great!

**Comment by lockedbyte** [comment]
Hi @sh1va73 !

As you suggested, I added a loop to keep program running. Whenever you want to exit in any menu you can select option 99 to exit, anyways you can always use abort keys (Ctrl+C).

Thanks for the suggestion!

Closing this issue now
